//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-04-22 11:56:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace RebelRentals
{
    public partial class Ship {

        public Ship()
        {
            this.Price = 0;
            this.NumberOfPopulation = 0;
            this.JunctionShipOrders = new List<JunctionShipOrder>();
            OnCreated();
        }

        public virtual int Id
        {
            get;
            set;
        }

        public virtual string Model
        {
            get;
            set;
        }

        public virtual string Class
        {
            get;
            set;
        }

        public virtual int MaxSpeed
        {
            get;
            set;
        }

        public virtual int Length
        {
            get;
            set;
        }

        public virtual int Width
        {
            get;
            set;
        }

        public virtual int Height
        {
            get;
            set;
        }

        public virtual double Price
        {
            get;
            set;
        }

        public virtual int NumberOfPopulation
        {
            get;
            set;
        }

        public virtual string About
        {
            get;
            set;
        }

        public virtual IList<JunctionShipOrder> JunctionShipOrders
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
