//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2020-04-22 11:56:03
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;

namespace RebelRentals
{
    public partial class AspNetUser {

        public AspNetUser()
        {
            this.AspNetUserRoles = new List<AspNetUserRole>();
            this.JunctionShipOrders = new List<JunctionShipOrder>();
            OnCreated();
        }

        public virtual string Id
        {
            get;
            set;
        }

        public virtual string UserName
        {
            get;
            set;
        }

        public virtual string NormalizedUserName
        {
            get;
            set;
        }

        public virtual string Email
        {
            get;
            set;
        }

        public virtual string NormalizedEmail
        {
            get;
            set;
        }

        public virtual bool EmailConfirmed
        {
            get;
            set;
        }

        public virtual string PasswordHash
        {
            get;
            set;
        }

        public virtual string SecurityStamp
        {
            get;
            set;
        }

        public virtual string ConcurrencyStamp
        {
            get;
            set;
        }

        public virtual string PhoneNumber
        {
            get;
            set;
        }

        public virtual bool PhoneNumberConfirmed
        {
            get;
            set;
        }

        public virtual bool TwoFactorEnabled
        {
            get;
            set;
        }

        public virtual System.DateTimeOffset? LockoutEnd
        {
            get;
            set;
        }

        public virtual bool LockoutEnabled
        {
            get;
            set;
        }

        public virtual int AccessFailedCount
        {
            get;
            set;
        }

        public virtual IList<AspNetUserRole> AspNetUserRoles
        {
            get;
            set;
        }

        public virtual IList<JunctionShipOrder> JunctionShipOrders
        {
            get;
            set;
        }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
